### PR TITLE
fix!: remove @aws-sdk types and client-s3 from peer dependencies

### PR DESCRIPTION
**Pull request by m-radzikowski**
NPM 7 installs peer dependencies automatically. This can cause installing newer version of the @aws-sdk/types than is required by other client libraries, and cause type conflicts.

We remove `@aws-sdk/types` and `@aws-sdk/client-s3` from peer dependencies.

`@aws-sdk/types` package is required anyway by the SDK client libs.

The `client-s3` lib is needed for `libStorage` mock functionality. Now, the `libStorage` is not imported in the main package `index.ts`, so lack of `client-s3` will not cause errors for users not needing it. The `mockLibStorageUpload` must be now imported as:

```ts
import {mockLibStorageUpload} from 'aws-sdk-client-mock/libStorage';
```

TODO:

- [x] wait for jest v28 release with https://github.com/facebook/jest/issues/9771 solved - until then, jest does not support package exports, and `import ... from 'aws-sdk-client-mock/libStorage'` fails
- [x] update README for `libStorage` mocking, including required jest version >= 28

Solves #56

### CODE REVIEW

**Comment by sekhavati** [comment]
Looking forward to seeing this go in 👍 We were trying to upgrade all our runtimes to Node v16 given the recent [AWS announcement](https://aws.amazon.com/blogs/compute/node-js-16-x-runtime-now-available-in-aws-lambda/) and started to encounter these issues

**Comment by m-radzikowski** [comment]
@sekhavati check out the freshly released v1.0.0 🙂

**Comment by sekhavati** [comment]
@m-radzikowski I've given this a fresh run today and unfortunately I'm still encountering similar issues regarding type conflicts as mentioned [here](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats). 

To give you some background:

- We were on `v0.6.2` of this library and Node v14 for a long time without any issues
- AWS released support for Node v16 so we attempted to upgrade our monorepo
- Upon doing so we immediately starting hitting the conflicting types error list above
- We're now on Jest `v28.1.1` and `v1.0.0` of this library but still get the same errors
- Each monorepo package declares its own `@aws-sdk/*` dependencies as needed (ie: not declared at the top level `package.json`), but across all packages they're on the same version (`v3.49.0` for us)
- I've tried installing `@aws-sdk/types` at the root level _and/or_ at individual package level but to no avail

I'll have to come back and revisit this again antoher time now, but rather short on ideas at the moment, other than perhaps try upgrading all the `@aws-sdk/*` packages across the board to the latest versions and seeing if that makes a difference. 

If you have any other suggestions please let me know! 

Thanks again for the effort that's gone into this library, it's awesome 👍

**Comment by sekhavati** [comment]
@m-radzikowski on a whim I thought I'd try regenerating all the `package-lock.json` files throughout the monorepo (given we pin our dependencies anyway) and low and behold everything now works 🙌 Not sure what was up with them but thought you might like to know! 

ps. above was without installing `@aws-sdk/types` explicitly either

**Comment by m-radzikowski** [comment]
@sekhavati great, I'm glad you solved it! Seems like npm did not clear no longer needed peer dependencies upon library version bump? Weird.

**Pull request merged**
