### PR TITLE
fix: Bump Sinon version

### PR DESCRIPTION
**Pull request by samchungy**
Resolves https://github.com/m-radzikowski/aws-sdk-client-mock/issues/130

I didn't have any issues running any existing tests or building using a yarn resolution for this version on my repo.

### CODE REVIEW

**Comment by m-radzikowski** [comment]
Thank you for the PR.

However, I don't think bumping the Sinon version resolves the #130.

I think the problem is not with the `sinon` itself, but with the `@types/sinon`. If you create an empty project, even without the `aws-sdk-client-mock` as a dependency, but with the latest versions of `sinon` and `@types/sinon`:

`package.json`:

```json
{
  "name": "sinon-test",
  "scripts": {
    "build": "tsc"
  },
  "devDependencies": {
    "@types/sinon": "10.0.13",
    "sinon": "14.0.2",
    "@types/node": "18.11.9",
    "typescript": "4.9.3"
  }
}
```

and try to transpile with `tsc` without the `compilerOptions.skipLibCheck` flag, you will still get the same errors:

```
> tsc

node_modules/@types/sinon/index.d.ts:1447:53 - error TS2694: Namespace '"/Users/mradzikowski/Documents/aws-sdk-client-mock-tests/sinon-aws-client-mock/node_modules/@sinonjs/fake-timers/types/fake-timers-src"' has no exported member 'FakeTimerInstallOpts'.

1447         useFakeTimers: boolean | Partial<FakeTimers.FakeTimerInstallOpts>;
                                                         ~~~~~~~~~~~~~~~~~~~~

node_modules/@types/sinon/index.d.ts:1569:67 - error TS2694: Namespace '"/Users/mradzikowski/Documents/aws-sdk-client-mock-tests/sinon-aws-client-mock/node_modules/@sinonjs/fake-timers/types/fake-timers-src"' has no exported member 'FakeTimerInstallOpts'.

1569         useFakeTimers(config?: number | Date | Partial<FakeTimers.FakeTimerInstallOpts>): SinonFakeTimers;
                                                                       ~~~~~~~~~~~~~~~~~~~~


Found 2 errors in the same file, starting at: node_modules/@types/sinon/index.d.ts:1447
```

**Comment by samchungy** [comment]
Huh strange my types are playing up then. Might have some residual versions hanging around. My bad

**Comment by samchungy** [comment]
Ah okay so this worked for me because bumping Sinon also bumped my @sinon/fake-timers version. It looks like the types package relies on it for types

**Comment by samchungy** [comment]
Hey @m-radzikowski, this actually seems to work. I've fixed the lockfile which was why the first build didn't work. 

https://github.com/samchungy/sinon-types with this repo I don't get type issues running `tsc`. When I changed it to this repo's version of sinon I get errors. :)

**Comment by m-radzikowski** [comment]
Thank you. My quick test previously was with npm and it did not install the newer `fake-timers` version on sinon version bump without calling `npm update` additionally, so I still was getting the errors... Here it all seems to work!

I will release it as 2.0.1 in a moment.

**Pull request merged**
