### PR TITLE
chore: bump sinon from 16.1.3 to 18.0.1

### PR DESCRIPTION
**Pull request by orien**
Bump sinon from 16.1.3 to 18.0.1

Changelog: https://github.com/sinonjs/sinon/blob/main/CHANGES.md

### CODE REVIEW

**Comment by curtdept** [comment]
LGTM, tests all pass

**Review by curtdept — APPROVED** [review]

**Comment by supreetkt** [comment]
Hello - waiting for this to be merged as this is a high severity vulnerability.

**Comment by psoleckimoj** [comment]
If you don't want to wait for this you can always add the following temporarily:

```
"overrides": {
    "aws-sdk-client-mock": {
      "sinon": "^18.0.1",
      "@types/sinon": "^17.0.3"
    }
  }
```

**Comment by m-radzikowski** [comment]
Released in [v4.0.2](https://github.com/m-radzikowski/aws-sdk-client-mock/releases/tag/v4.0.2)

**Pull request merged**
